# yaml-language-server: $schema=https://code.kx.com/insights/enterprise/packaging/schemas/package.json#/$defs/Manifest
uuid: 1990233a-ea17-4951-ac78-47893a674108
name: custom
version: 1.0.0
dependencies: []
metadata:
  authors:
  - name: me
  pakxtime: '2025-05-29T18:36:42.685488'
entrypoints:
  aggregator: agg.q
  data-access: da.q
system:
  _pakx_version: 1.13.1
tables: {}
databases: {}
pipelines: {}
views: {}
patches: []
