{
 "title": "Ingest Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Messages Out - RT",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "kxi_rt_out_messages_total", "legendFormat": "rt out messages" },
    { "expr": "kxi_rt_in_messages_total", "legendFormat": "rt in messages" }
   ]
  },
  {
   "title": "Number of Msgs received - RDB, IDB, HDB",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "kxi_da_stream_msgs{instance=\"rdb-sidecar:8080\"}",
     "legendFormat": "rdb messages"
    },
    {
     "expr": "kxi_da_stream_msgs{instance=\"idb-sidecar:8080\"}",
     "legendFormat": "idb messages"
    },
    {
     "expr": "kxi_da_stream_msgs{instance=\"hdb-sidecar:8080\"}",
     "legendFormat": "hdb messages"
    }
   ]
  },
  {
   "title": "Query Requests - DA, SG, RC, AGG",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "kxi_da_requests", "legendFormat": "{{instance}} - da requests" },
    { "expr": "kxi_sg_ipc_requests_total", "legendFormat": "sg requests" },
    { "expr": "kxi_rc_reqs_total", "legendFormat": "rc requests" },
    { "expr": "kxi_agg_ipc_reqs", "legendFormat": "agg requests" }
   ]
  },
  {
   "title": "Database Services RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "memory_usage_bytes", "legendFormat": "{{instance}} - Memory usage" }
   ]
  }
 ]
}